[project]
name = "skybrush-ext-libmotioncapture"
version = "1.1.0"
description = "libmotioncapture mocap support for Skybrush Server"
authors = [{ name = "Tamas Nepusz", email = "ntamas@gmail.com" }]
license = "LicenseRef-Proprietary"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"
depedencies = [
  "quart>=0.18.0",
  "motioncapture>=1.0a2",
  "numpy>=2.0.0"
]

[dependency-groups]
dev = [
  "flockwave-server>=2.36.1"
]

[project.entry-points."skybrush.server.ext"]
libmotioncapture = "skybrush_ext_libmotioncapture"

[[tool.uv.index]]
name = "fury"
url = "https://pypi.fury.io/skybrush/"

[tool.uv.sources]
flockwave-server = { index = "fury" }

[tool.ruff]
lint.ignore = ["B905", "C901", "E402", "E501"]
lint.select = ["B", "C", "E", "F", "W"]

[build-system]
requires = ["uv_build>=0.8.0"]
build-backend = "uv_build"
